Updating the action

diff --git a/.github/workflows/deploy-to-eks.yaml b/.github/workflows/deploy-to-eks.yaml
--- a/.github/workflows/deploy-to-eks.yaml
+++ b/.github/workflows/deploy-to-eks.yaml
@@ -1,25 +1,20 @@
 name: Create EKS cluster, deploy kubeflow-mlflow Terraform solution and run UATs
+
 on:
+  pull_request: {}
   workflow_dispatch:
     inputs:
       k8s_version:
-        description: 'Kubernetes version to be used for the EKS cluster. Make sure that the corresponding K8s version is supported by the cloud.'
+        description: 'Kubernetes version to use for the EKS cluster (e.g. 1.27)'
         required: false
       uats_branch:
-        description: 'Branch to run the UATs from e.g. main or track/1.10. By default, this is defined by the dependencies.yaml file.'
+        description: 'Branch to run the UATs from, e.g., main or track/1.10'
         required: false
   schedule:
     - cron: "17 02 * * 1"
 
 env:
   CLUSTER_NAME: kubeflow-eks
-  AWS_REGION: ${{ secrets.AWS_REGION }}
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  JUJU_CONTROLLER: kubeflow-controller
-  JUJU_MODEL: kubeflow
-  CKF_CHANNEL: "1.10/stable"
-  MLFLOW_CHANNEL: "latest/stable"
 
 jobs:
   deploy-solution-to-eks:
@@ -28,61 +23,85 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
-      - name: Set envvars from dependencies.yaml
+      - name: Set environment variables (from dependencies.yaml and inputs)
         run: |
-          yq eval 'to_entries | .[] | "\(.key)=\(.value)"' ".github/dependencies.yaml" | while IFS= read -r line; do
-            echo "$line" >> "$GITHUB_ENV"
-          done
+          eval $(yq eval 'to_entries | .[] | "\(.key)=\(.value)"' ".github/dependencies.yaml")
 
-      - name: Update ENV variables from inputs if available
+          FINAL_K8S_VERSION="${{ inputs.k8s_version }}"
+          FINAL_K8S_VERSION=${FINAL_K8S_VERSION:-$K8S_VERSION}
+
+          FINAL_UATS_BRANCH="${{ inputs.uats_branch }}"
+          FINAL_UATS_BRANCH=${FINAL_UATS_BRANCH:-$UATS_BRANCH}
+
+          echo "K8S_VERSION=$FINAL_K8S_VERSION" >> $GITHUB_ENV
+          echo "UATS_BRANCH=$FINAL_UATS_BRANCH" >> $GITHUB_ENV
+
+      - name: Extract AWS region from cluster.yaml
         run: |
-          K8S_VERSION=${{ inputs.k8s_version || env.K8S_VERSION }}
-          echo "K8S_VERSION=${K8S_VERSION}" >> $GITHUB_ENV
-          UATS_BRANCH=${{ inputs.uats_branch || env.UATS_BRANCH }}
-          echo "UATS_BRANCH=${UATS_BRANCH}" >> $GITHUB_ENV
+          REGION=$(yq e '.metadata.region' .github/cluster.yaml)
+          echo "AWS_REGION=$REGION" >> $GITHUB_ENV
 
       - name: Install CLI tools & dependencies
         run: |
           pip install tox
-          sudo snap install juju --channel=${{ env.JUJU_VERSION }}/stable
+          sudo snap install juju --classic
           sudo snap install charmcraft --classic
-          sudo snap install terraform  --channel latest/stable --classic
+          sudo snap install terraform --classic
           juju version
           terraform --version
-          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin
-          curl -LO "https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/amd64/kubectl"
-          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Create EKS Cluster
+      - name: Install kubectl
         run: |
-          eksctl create cluster \
-            --name $CLUSTER_NAME \
-            --region $AWS_REGION \
-            --version $K8S_VERSION \
-            --nodegroup-name standard-workers \
-            --node-type t3.large \
-            --nodes 3 \
-            --nodes-min 3 \
-            --nodes-max 5 \
-            --managed
+          sudo snap install kubectl --classic --channel=${{ env.K8S_VERSION }}/stable
+          mkdir ~/.kube
+          kubectl version --client
 
-      - name: Update kubeconfig
-        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
-
-      - name: Add EKS cluster to Juju
+      - name: Install eksctl
         run: |
-          juju version
-          juju add-k8s eks --client
+          PLATFORM=$(uname -s)_amd64
+          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_${PLATFORM}.tar.gz" | tar xz -C /tmp
+          sudo mv /tmp/eksctl /usr/local/bin
+          eksctl version
+
+
+      - name: Pre-delete EKS cluster if exists
+        run: |
+          echo "Cleaning up old cluster (if any)..."
+          eksctl delete cluster --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }} || echo "Cluster not found or already deleted."
+
+      - name: Pre-delete CloudFormation stack if exists
+        run: |
+          echo "Cleaning up old CloudFormation stack (if any)..."
+          aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name eksctl-${{ env.CLUSTER_NAME }}-cluster || echo "Stack not found."
+
+      - name: Create EKS cluster
+        run: |
+          yq e ".metadata.name |= \"${{ env.CLUSTER_NAME }}\"" -i .github/cluster.yaml
+          yq e ".metadata.version |= \"${{ env.K8S_VERSION }}\"" -i .github/cluster.yaml
+
+          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
+          eksctl create cluster -f .github/cluster.yaml
+          kubectl get nodes
+
+      - name: Configure EKS nodes
+        run: |
+          echo "Configuring sysctl on EKS workers"
+          source ./scripts/gh-actions/set_eks_sysctl_config.sh
+
+      - name: Setup Juju controller
+        run: |
+          /snap/juju/current/bin/juju add-k8s eks --client
           juju bootstrap eks eks-controller
+          juju add-model kubeflow
 
       - name: Deploy and assert kubeflow-mlflow solution
         run: |
@@ -95,46 +114,49 @@ jobs:
           git checkout ${{ env.UATS_BRANCH }}
           tox -e uats-remote -- --filter "not feast"
 
-      # On failure, capture debugging resources
-      - name: Select model
-        run: juju switch eks-controller:kubeflow
+      - name: Select model (for debug)
         if: failure() || cancelled()
+        run: juju switch eks-controller:kubeflow
 
       - name: Save debug artifacts
-        uses: canonical/kubeflow-ci/actions/dump-charm-debug-artifacts@main
         if: failure() || cancelled()
+        uses: canonical/kubeflow-ci/actions/dump-charm-debug-artifacts@main
 
       - name: Get juju status
-        run: juju status
         if: failure() || cancelled()
+        run: juju status
 
       - name: Get juju debug logs
+        if: failure() || cancelled()
         run: juju debug-log --replay --no-tail
-        if: failure() || cancelled()
 
-      - name: Get all kubernetes resources
-        run: kubectl get all -A
+      - name: Get all Kubernetes resources
         if: failure() || cancelled()
+        run: kubectl get all -A
 
       - name: Describe all pods
         if: failure() || cancelled()
         run: kubectl describe pods --all-namespaces
 
-      - name: Get logs from pods with status = Pending
-        run: kubectl -n kubeflow get pods | tail -n +2 | grep Pending | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
+      - name: Logs from Pending pods
         if: failure() || cancelled()
+        run: |
+          kubectl -n kubeflow get pods | tail -n +2 | grep Pending | awk '{print $1}' | xargs -r -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
 
-      - name: Get logs from pods with status = Failed
-        run: kubectl -n kubeflow get pods | tail -n +2 | grep Failed | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
+      - name: Logs from Failed pods
         if: failure() || cancelled()
+        run: |
+          kubectl -n kubeflow get pods | tail -n +2 | grep Failed | awk '{print $1}' | xargs -r -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
 
-      - name: Get logs from pods with status = CrashLoopBackOff
-        run: kubectl -n kubeflow get pods | tail -n +2 | grep CrashLoopBackOff | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
+      - name: Logs from CrashLoopBackOff pods
         if: failure() || cancelled()
+        run: |
+          kubectl -n kubeflow get pods | tail -n +2 | grep CrashLoopBackOff | awk '{print $1}' | xargs -r -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
 
       - name: Delete EKS cluster
         if: always()
-        run: |
-          VERSION=${{ matrix.bundle_version }}
-          VERSION_WITHOUT_DOT="${VERSION//.}"
-          eksctl delete cluster --region eu-central-1 --name=kubeflow-test-$VERSION_WITHOUT_DOT
+        run: eksctl delete cluster --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
+
+      - name: Delete CloudFormation stack (if present)
+        if: always()
+        run: aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name eksctl-${{ env.CLUSTER_NAME }}-cluster
